kind: pipeline
type: docker
name: default
steps:
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 172.31.41.62
    username: ubuntu
    port: 22
    key:
      from_secret: ssh_key
    script:
      - ls
      - export LAST_BUILD_NUMBER=`expr ${DRONE_BUILD_NUMBER} - 1`
      - sudo chown ubuntu:ubuntu /var/run/docker.sock
      - docker stop cms-ui-bv${LAST_BUILD_NUMBER}
      - echo $LAST_BUILD_NUMBER 
  when:
    branch:
    - master
    event:
    - push
    - pull_request
