kind: pipeline
type: docker
name: default
steps:
- name: build-cms-ui
  image: node
  commands:
    - ls
    - npm install
    - npm run build
    - ls
  when: 
    branch: 
    - master
    event:
    - push
    - pull_request
