kind: pipeline
type: docker
name: default
steps:
- name: build-cms-ui
  image: node:14-alpine
  commands:
    - node -v
    - npm -v
    - ls
 #trigger:
  when:
    branch: 
      include:
        - master
    event:
    - push
