kind: pipeline
type: docker
name: default
steps:
- name: build-cms-ui
  image: node:14-alpine
  commands:
    - ls
    - ls
    - node -v
    - npm -v
    - ls
- name: test
  image: node:14-alpine
  commands:
    - node -v
    - npm -v
    - ls
trigger:
  branch:
  - master
  event:
  - push
